CREATE TABLE users (
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    points INT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

--@block
SELECT * FROM users
